name: python wheel package build

on:
  push:
    branches:
      - master

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04, windows-2022, macos-13]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
      - name: Checkout CaDiCaL
        uses: actions/checkout@v3
        with:
          repository: meelgroup/cadical
          ref: 'add_dynamic_lib'
          path: python/cadical

      - name: Checkout Cadiback
        uses: actions/checkout@v3
        with:
          repository: meelgroup/cadiback
          ref: 'mate'
          path: python/cadiback

      - name: configure and build CaDiCaL
        run: cd python/cadical && CXXFLAGS=-fPIC ./configure --competition && make -j4

      - name: Configure and build Cadiback
        run: cd python/cadiback && ./configure && make -j4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          CIBW_BEFORE_ALL_LINUX: yum install -y gmp-devel
          CIBW_SKIP: "*musl*"
          CIBW_ARCHS: "auto64"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
      - name: Install twine
        run: python -m pip install twine
      - name: Publish wheels to PyPI 
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --skip-existing --disable-progress-bar ./wheelhouse/pycryptosat-*.whl
